apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: builder
  spec:
    lookupPolicy:
      local: true
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: builder
    name: builder
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: builder:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |-
        FROM registry.access.redhat.com/rhoar-nodejs/nodejs-8

        USER root

        RUN yum-config-manager --enable rhel-server-rhscl-7-rpms

        RUN yum install -y rubygems rh-git29 && yum clean all && gem install asciidoctor -v 1.5.7

        RUN echo "source scl_source enable rh-git29" >> /opt/app-root/etc/scl_enable

        USER 1001
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: zzalFwaFe4yHFSEs0zRu
      type: GitHub
    - generic:
        secret: 0TYRk5fZGhiaM4Lt4BRi
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
